### ISSUE TITLE
 hyperscan::chimera::Scratch the trait `Send` is not implemented for `NonNull<ch_scratch>`

### ISSUE THREAD

**Issue by 0x003e** [flier/rust-hyperscan#13]
Hi every one, 

Firstly thank you for this Rust hyperscan binding.

I whant to init hypercan **scratch**  struct in lazy_static.
https://github.com/flier/rust-hyperscan/blob/7665585732d9170ebe04f5518f30e71b5827399b/hyperscan/src/runtime/scratch.rs#L13

Howerver this struct not implement the trait Send:

```rust
19 |   pub struct Lazy<T: Sync>(Cell<Option<T>>, Once);
   |                      ---- required by this bound in `lazy_static::lazy::Lazy`
   |
   = help: within `hyperscan::chimera::Scratch`, the trait `Send` is not implemented for `NonNull<ch_scratch>`
   = note: required because it appears within the type `hyperscan::chimera::Scratch`
   = note: required because of the requirements on the impl of `Send` for `tokio::sync::RwLock<hyperscan::chimera::Scratch>`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `Arc<tokio::sync::RwLock<hyperscan::chimera::Scratch>>`
   = note: required because it appears within the type `LogParser`
```

It possible to implement the trait Send for this struct ? (I am a beginner with rust FFI bindings)

**Comment by flier** [comment]
First of all, I don't think it's a good idea to put `Scratch` in a global variable, the [scratch space](https://intel.github.io/hyperscan/dev-reference/runtime.html#scratch-space) can be shared with multiple databases, but it should only be used in one scanning task.

> While the Hyperscan library is re-entrant, the use of scratch spaces is not. For example, if by design it is deemed necessary to run recursive or nested scanning (say, from the match callback function), then an additional scratch space is required for that context.

Even so, implement  the trait`Send` is make sense, I will add it soon.

Thanks
