### ISSUE TITLE
Release 0.1.8?

### ISSUE THREAD

**Issue by dvaldivia** [flier/rust-hyperscan#3]
Hi, I wanted to use Hyperscan constant `HS_FLAG_COMBINATION` and I see it was merged on August 2018, but the last crate `0.1.7` was released on July 2018, I was wondering when will a release `0.1.8` would be issued

**Comment by flier** [comment]
Sorry for the delay, I'm working on the `v0.2` branch recently, I will back and publish `0.1.8` ASAP.
