### ISSUE TITLE
Install C library first?

### ISSUE THREAD

**Issue by ahopkins** [flier/rust-hyperscan#4]
I am trying to use `rust-hyperscan`  in a library. When I run `cargo build` it complains that

```
error: failed to run custom build command for `hyperscan-sys v0.1.8`

Caused by:
  process didn't exit successfully: `/home/adam/Projects/Hyprtr/hyprtr/target/debug/build/hyperscan-sys-331b062cacfff398/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'please install hyperscan from https://github.com/01org/hyperscan', /home/adam/.cargo/registry/src/github.com-1ecc6299db9ec823/hyperscan-sys-0.1.8/build.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Is it looking for the `hyperscan` C library to be built already? Is `cargo` capable of compiling C libraries?

**Comment by flier** [comment]
sure, `rust-hyperscan` depends on the `hyperscan` C library, you can install from source or your favorite package manager. https://www.hyperscan.io/downloads/
