### ISSUE TITLE
Is dynamic linking rust-hyperscan used?

### ISSUE THREAD

**Issue by Kaiser925** [flier/rust-hyperscan#8]
Is rust-hyperscan linked to hyperscan using the dynamic link?
If yes, is there a way to use static linking by passing any parameters?

**Comment by Kaiser925** [comment]
I am building a rust static library, it used rust-hyperscan. It build success, and I got the .a file,  but when I try to use my library, I got error like this:
```
xxx.a: in function `core::ptr::real_drop_in_place':
undefined reference to `hs_free_scratch'
...
``` 
Is there something I didn’t do right when I used it?

**Comment by eliaslevy** [comment]
See https://github.com/eliaslevy/rust-hyperscan/commits/static

**Comment by Kaiser925** [comment]
Thanks, @eliaslevy , it worked.
