### ISSUE TITLE
change scan_mut api into using &self instead of &mut self

### ISSUE THREAD

**Issue by JackLiar** [flier/rust-hyperscan#9]
While scanning, the database struct should not be modified, so we should not use mutable reference in the scan_mut api.

What actually needs to be mutable is the context data.

**Comment by flier** [comment]
@JackLiar I'm working on [a new API](https://github.com/flier/rust-hyperscan/blob/v0.2/hyperscan/src/runtime/scan.rs#L35), you might want to take a look and give suggestions, thanks
